const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  await prisma.event.createMany({
    data: [
      { label: 'Nossa primeira conversa', date: new Date('2020-12-17'), description: 'Foi pelo Tinder que nos conhecemos, por volta de novembro/dezembro de 2020. Pode não parecer uma forma romântica de se conhecer, mas a história tem mais partes. Eu sofria muito de ansiedade na época e não conseguia manter uma simples conversa com quem eu dava match no Tinder. Eu vivia num ciclo de desinstalar e instalar o aplicativo, mas quando dei match com você e começamos a conversar, aquela ansiedade simplesmente desapareceu. Nossa conversa foi tão natural, sempre me fazia rir e sua beleza me deixou sem fôlego. Não acreditava que tinha conseguido dar um match com uma mulher tão perfeita. Não temos nenhum print de nossas conversas no Tinder e não sabemos exatamente a data que demos match, mas esta foi a data que começamos a conversar pelo whatsapp e desde então não passamos um único dia sem falar com o outro', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//17_12_2020.png' },
      { label: 'Nosso primeiro encontro', date: new Date('2021-01-07'), description: 'Depois de algumas semanas conversando por mensagem, queríamos nos encontrar pessoalmente. Mas estávamos na pandemia e morrendo de medo de sair de casa para qualquer coisa, eu mesmo tinha acabado de voltar de Fazenda Nova. Passei vários meses isolados lá pelo medo do vírus. Então marcamos um date seguro, usando máscara, passando álcool em gel e combinamos de manter a distância neste encontro. Lembro que formos ver o filme Mulher-Maravilha 1984 no shopping Rio Verde e você chegou primeiro. Eu ainda não tinha carteira, então foi de uber e acabei demorando mais para chegar. Esse foi o primeiro dia que nos vemos pessoalmente e foi o dia que me apaixonei mais ainda por você', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//07_01_2021.png' },
      { label: 'Nosso primeiro beijo', date: new Date('2021-01-14'), description: 'Depois do primeiro encontro, tivemos mais coragem para sair novamente e dessa vez sermos um pouco menos cuidadosos e ficar mais a vontade um com o outro. Então fomos novamente no cinema e vimos um filme bem genérico chamado Legado Explosivo. Fiquei tão nervoso o filme todo até tomar coragem para te beijar. O que senti na hora que juntei coragem o suficiente é impossível de descrever em palavras, é o mesmo sentimento que sinto sempre que te beijo. Uma explosão de felicidade e gratidão. Eu estava tão nervoso que nem prestei atenção no filme e até hoje não sei nada sobre ele. Não sabia nem o nome, tive que fazer uma baita pesquisa pelas nossas conversas para conseguir achar. Foi um dia muito especial e tudo graças a você, a mulher mais linda e incrível do mundo', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//14_01_2021.png' },
      { label: 'O começo do nosso namoro', date: new Date('2021-02-12'), description: 'Pouco tempo depois de nos conhecermos, eu já sabia que queria você só para mim. Não perdi tempo e comecei a conversar com você sobre namoro, lembro até de perguntar se você aceitaria namorar comigo se eu te pedisse em namoro e sua resposta foi "sim". Então já comecei os preparativos e vi uma oportunidade única, te pedi em namoro em uma data palíndroma: 12/02/2021 que ao contrário continua sendo a mesma data. Pedi ajuda para alguns amigos do ensino médio, encomendei uma sobremesa em formato de coração e fomos ao Le Pinguê. Lembro de ficar muito nervoso, mesmo sabendo que você aceitaria. Acho que é normal ficar nervoso quando estamos falando de amor, e que bom que você aceitou. Naquele dia, você me fez o homem mais feliz do mundo e continuo assim sempre que estou do seu lado', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_02_2021.png' },
      { label: 'Nosso primeiro mês de namoro', date: new Date('2021-03-12'), description: 'Um mês de namoro e eu estava sob suspeita de covid. Estávamos doidos para comemorar, mas alguém que tive contato ficou com covid e o resultado do meu teste não tinha saído ainda. Então fizemos uma simples troca de presentes, todos muito bem higienizados com álcool. O presente que você me deu é um que uso até hoje: uma caneca em referência ao The Office, que em vez de "Melhor chefe do mundo" está escrito "Melhor namorado do mundo" em inglês e com a palavra chefe riscada. Esse foi o primeiro dos presentes que você me deu e que foi feito com muito carinho. É minha caneca preferida e sempre a uso para tomar chá', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_03_2021.png' },
      { label: 'Nosso primeiro dia dos namorados', date: new Date('2021-06-12'), description: 'Era nosso 4º mês de namoro e dia dos namorados, e de novo estávamos isolados por conta do covid, mas fizemos a troca de presentes no mesmo dia. O prente que você me deu foi tão lindo, uso a caixa dele até hoje na minha mesa. Só não a uso para guardar as cartas que recebi, pois muitas não cabem dentro dela e teria que dobrar, mas a deixo na minha mesa como apoio do meu monitor e a vejo todo os dias. Essa caixa com um coração entalhado deixa a minha mesa com um ar mais leve e bonito e me deixa muito feliz sempre que a vejo', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_06_2021.png' },
      { label: 'Nossa primeira vacina de covid', date: new Date('2021-08-19'), description: 'Esse foi o dia que finalmente tomamos a vacina do covid, você foi tomar primeiro por conta da nossa diferença de idade e eu tomei somente alguns dias depois. Esse foi o fim do medo, o fim dos isolamentos. Nunca mais precisaríamos passar um feriado longe por conta do maldito covid. A vacinação foi feita na UniRV e fomos juntos nos dois dias', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//19_08_2021.png' },
      { label: 'Primeira viagem para fazenda nova', date: new Date('2021-09-04'), description: 'Nossa primeira viagem juntos, nessa viagem você finalmente conheceu Fazenda Nova e meus parentes maternos. Todos ficaram tão encantados com você e foi tão bom passar aqueles dias com você na fazenda. Nessa viagem, a lilica foi junto e lembro que ela estava morrendo de ciúmes. Não nos deixava sozinhos de jeito nenhum, até quando saímos para fazer uma caminhada ela nos seguiu. Lembro de descansarmos depois de subir um morro quando ouvimos a lilica chegando sem fôlego correndo atrás de nós', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//04_09_2021.png' },
      { label: 'Festa à fantasia de aniversário', date: new Date('2021-10-30'), description: 'Minha festa de aniversário de 20 anos foi à fantasia e fomos com uma fantasia de casal. Fomos de personagens de Harry Potter, eu de Snape por causa do meu cabelo longo e você de Bellatrix. Foi uma festa tão divertida e planejar essas fantasias com você me deixou muito feliz. Acho que nossas fantasias ficaram incríveis e combinamos muito bem', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//30_10_2021.png' },
      { label: 'Nossa primeira corrida da UniRV', date: new Date('2021-11-24'), description: 'A primeira de muitas corridas da UniRV. Mas como nós dois somos sedentários, fizemos somente o percurso da caminhada. Quem sabe um dia podemos começar a treinar para fazer a corrida em si, seria muito divertido fazer isso com você', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//24_11_2021.png' },
      { label: 'Nosso primeiro ano novo juntos', date: new Date('2021-12-31'), description: 'Esse foi o primeiro de muitos anos novos que passamos juntos. Nesse ano novo, passamos na sua casa com a sua família e foi uma noite muito especial', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//31_12_2021.png' },
      { label: 'Primeira viagem para caldas novas', date: new Date('2022-01-03'), description: 'Poucos dias depois do ano novo, fizemos uma viagem para calda novas e foi mais uma viagem maravilhosa ao seu lado. Passeamos bastante, nadamos um pouco e foi muito bom. Lembro de levar o computador para participar de um Happy Hour virtual da empresa que eu trabalhava remoto. Eu odiava esses eventos online, ainda bem que foi por pouco tempo e depois passamos muito tempo juntos', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//03_01_2022.png' },
      { label: 'Nosso primeiro ano de namoro', date: new Date('2022-02-12'), description: 'Nossa comemoração de 1 ano de namoro foi bem especial para mim, foi o dia que conheci sua família na fazenda da sua vó. Aquele dia foi bem assustador para mim, eram muitas pessoas e estava com muito medo de não gostarem de mim. Mas todos foram muito gentis e me senti bem, até bebi cachaça com seu tio. Você ficou preocupada de eu me assustar com uma família tão grande, mas estou acostumado com uma família assim e achei muito bom conhecer a todos', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_02_2022.png' },
      { label: 'Nossa aliança de namoro', date: new Date('2022-03-10'), description: 'Depois de muito tempo pesquisando, e depois de termos encomendado nossas alianças, esse foi o dia que as pegamos e começamos a utilizá-la. Eu iria para Brasília depois de alguns meses e eu queria algo que me lembrasse de você. A aliança foi o objeto perfeito para isso e acho as nossas tão bonitas. Estou ansioso para irmos atrás da nossa próxima aliança', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//10_03_2022.png' },
      { label: 'Nossa primeira vez jogando catan', date: new Date('2022-05-01'), description: 'Ganhei o jogo de tabuleiro Catan depois de ministrar alguns treinamentos sobre Gamificação e fiquei muito animado com meu primeiro jogo de tabuleiro. Quando criança já tive outros, mas este foi o primeiro jogo de tabuleiro mais complicado que ganhei e o primeiro que eu jogava há anos. Quando jogamos catan neste dia, nunca pensei que esse jogo seria tão importante para a gente. Gostamos tanto do jogo que começamos a jogar até a versão digital enquanto eu estava em Brasília. Agora jogamos menos ele, mas ainda continua um dos nossos jogos favoritos. Em 2024, um ano antes do que estou escrevendo este texto, você me presenteou com uma expansão desse jogo que o deixou muito mais legal (e bem mais complicado). Já jogamos bastante ele e ainda jogaremos muito mais', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//01_05_2022.png' },
      { label: 'Festa de aniversário/despedida', date: new Date('2022-10-27'), description: 'Foi o aniversário que ganhei o livro "O Iluminado" e esse foi o ano que voltei para Brasília, estava lá desde o começo do ano . Foi um ano bem difícil, nada fácil ficar longe de você meu amor. Mas ao mesmo tempo, o nosso relacionamento me deu forças para aguentar a pressão e ansiedade que a faculdade estava gerando. Sem o seu apoio, sem você ao meu lado, teria sido muito mais difícil. Esse foi o dia que fomos comemorar meu aniversário de 21 anos, no próximo dia eu já iria voltar para Brasília. Foi como uma despedida também, mas não gosto de chamar de despedida pois eu sempre voltarei e um dia iria voltar de vez, assim que eu me forma na faculdade e ficar livre dela de uma vez por todas', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//27_10_2022.png' },
      { label: 'Nosso primeiro natal juntos', date: new Date('2022-12-25'), description: 'Passamos o natal juntos em fazenda nova, foi muito bom passar o natal junto com você. Esse é um dos meus feriados favoritos e passar ele ao seu lado o deixou muito melhor', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//25_12_2022.png' },
      { label: 'Nossa primeira viagem à Brasília', date: new Date('2022-12-31'), description: 'Passamos uma semana juntos em Brasília e foram os melhores dias que passei naquela cidade. Fizemos vários passeios e até fomos na aula de felicidade juntos. Lembro de ficar muito triste depois que você voltou para Rio Verde, você deixou Brasília bem melhor e queria muito que ficasse comigo', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//31_12_2022.png' },
      { label: 'Nossa primeira viagem à Goiânia', date: new Date('2023-05-21'), description: 'Desde que minha vó paterna faleceu, antes de nos conhecermos, eu não ia tanto para Goiânia. Imagino que por isso demorou tanto para você conhecer minha família paterna. Todos adoraram te conhecer e ficaram encantadas com sua beleza e simpatia <3<3', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//21_05_2023.png' },
      { label: 'Nosso terceiro dia dos namorados', date: new Date('2023-06-12'), description: 'Nesse dia, eu estava em Rio Verde e conseguimos passar o dia juntos. Queríamos ter ido ao Nardela, mas estava fechado. Então fomos no route 64 e lembro do restaurante inteiro estar decorado para o dia dos namorados. Foi uma noite incrível e muito romântica', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_06_2023.png' },
      { label: 'Nossa segunda visita à Brasília', date: new Date('2023-07-22'), description: 'Nesse dia, você foi com meus pais me visitar em Brasília e levaram junto a chiquita filhotinha. Foi nessa viagem que a chiquita fez xixi no seu ombro durante a viagem. Ela era muito pequena e amava subir no ombro da gente e foi numa dessas subidas que ela não aguentou e fez o xixi. Nunca irei esquecer essa história kkkkkkk', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//22_07_2023.png' },
      { label: 'Filme da Barbie', date: new Date('2023-08-01'), description: 'Nunca vou esquecer de quando fomos ver o filme da barbie. Tentamos ir de rosa, mas nenhum de nós dois tinha um roupas totalmente rosa. Até tive que pegar uma camiseta emprestada da Naira do Jão que era preta com uma frase rosa. Gostei demais de ter visto o filme, ainda mais com você ao meu lado', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//01_08_2023.png' },
      { label: 'Show do Tiago Santineli', date: new Date('2024-01-25'), description: 'Você sempre foi fã do Tiago Santineli, e me mostrando os vídeos dele, acabei gostando bastante do conteúdo dele. Então, para a nossa surpresa, ele decidiu fazer um show bem aqui em Rio Verde. Ficamos tão felizes e animados, compramos os ingressos e no dia estávamos muito ansiosos. Chegamos tão cedo, por medo de ter uma fila gigantesca, que fomos os primeiros a chegar. O Show foi muito engraçado e no fim conseguimos tirar fotos com ele. Até hoje fico chateado que a minha foto não ficou tão legal, ele estava mostrando o dedo do meio apra a foto com todo mundo e quando chegou a minha vez, ele não mostrou e eu não vi. Então ficou somente eu mostrando o dedo e ele não, o que me faz parecer um babaca. Mesmo assim, consegui tirar outras fotos legais com ele e foi uma noite incrível. Ainda mais com você do meu lado', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//25_01_2024.png' },
      { label: 'Nosso terceiro ano de namoro', date: new Date('2024-02-12'), description: 'Foi muito bom esse aniversário pis fizemos uma mini festa, somente para nós dois. Encomendados um bolo e docinhos, como uma festa de criança. Foi mais um dia muito especial e maravilhoso ao seu lado e espero que todos os próximos anos também sejam incríveis desse mesmo jeito', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_02_2024.png' },
      { label: 'Show do Louis Tomlinson', date: new Date('2024-05-11'), description: 'Foi a primeira vez que fomos em um show juntos! Foi tão bom te ver feliz ao ver um dos seus ídolos e fiquei muito feliz de estar ao seu lado num evento tão especial. Foi nessa viagem que perdemos o horário do voo de volta (culpa minha :c), mas ainda bem que o moço do viação teve dó da gente e nos colocou no próximo voo que tinha', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//11_05_2024.png' },
      { label: 'Upgrade no Catan', date: new Date('2024-11-02'), description: 'Foi no meu aniversário de 22 anos que você me deu a expansão do Catan que deixou o nosso jogo favorito ainda melhor (e um pouco mais complicado tamém kkkkkk). Esse jogo foi tão marcante para nós e eu amei este presente', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//02_11_2024.png' },
      { label: 'Show do Twenty One Pilots', date: new Date('2025-01-26'), description: 'Este show foi muito importante para mim e você foi a responsável por deixá-lo ainda mais especial. Se não fosse você, eu não teria visto a banda passar pertinho de mim. Você foi muito esperta no dia para ver que os palcos secundário e passarelas estavam sem ninguém enquanto estavam no palco principal, enquanto eu estava paralisado pelo show. Sempre serei grato por você ter deixado esse dia ainda mais especial', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//26_01_2025.png' },
      { label: 'Nosso quarto ano de namoro', date: new Date('2025-02-12'), description: 'Eu estava em Brasília nesse dia, mas foi um dia muito especial para nós. Quatro anos que passaram tão rápido, tanta coisa aconteceu. E definitivamente foram os quatro melhores anos da minha vida. Você me transformou, me deixou mais feliz e me fez uma pessoa melhor. Acabamos por comemorar quando voltei no dia 20 de fevereiro, quando você me deu a garrafa e o cd do Twenty One Pilots, presentes que amei <3<3', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_02_2025.png' },
      { label: 'Nossa terceira visita à Brasília', date: new Date('2025-04-12'), description: 'Passamos a semana do saco cheio em Brasília e de novo foi muito bom ter você comigo lá. Sempre que você me visita em Brasília, deixa o lugar mais agradável. Também fizemos pela primeira vez nossos próprios ovos de páscoa e foi uma experiência incrível! Aprendemos bastante e no próximo ano faremos ovos de páscoas ainda melhores!', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_04_2025.png' },
      { label: 'Nosso quinto dia dos namorados', date: new Date('2025-06-12'), description: 'Depois de 4 anos juntos, eu ainda me sinto o homem mais feliz do mundo e por isso eu queria demonstrar toda a minha gratidão e alegria neste dia. Planejei algo muito especial, comprei um lírio para cuidarmos juntos, o livro de colorir dos ursinhos para pintarmos juntos e salgadinhos para vermos o filme do nosso primeiro beijo novamente. Foi um dia tão especial e foi o dia que mostrei essa nova atualização de linha do tempo do nosso site. Agora teremos algo para nos lembrarmos dos nossos melhores momentos para sempre e fiquei tão feliz de poder proporcionar isso, finalmente usando minahs habilidades de programação. Eu te amo muito meu amor <3<3<3', imageUrl: 'https://vykcaezbaaokfpzflldq.supabase.co/storage/v1/object/public/anairam-assets//12_06_2025.png' },
    ],
    skipDuplicates: true
  });
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
