name: Deploy DB to Supabase

on:
  push:
    branches: [ main ]

jobs:
  migrate_and_seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run migrations on Supabase
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
          DEBUG: 'prisma:migrate*'
        run: npx prisma migrate deploy

      - name: Run seed on Supabase
        if: always()
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: npx prisma db seed
